baseURL = '/'
languageCode = 'en-us'
title = 'RoyLab: Code & Web'
theme = 'ananke'

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
pagination = 9 


[author]
  name = "Malick Royce LAYINDE"
  email = "layinderoyce@gmail.com"
  
[params]
  copyright = "Copyright © 2023 Malick Royce LAYINDE"
  recent_posts_number = 4

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
