baseURL = '/'
languageCode = 'en-us'
title = 'RoyLab: Code & Web'
theme = 'ananke'

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
tags = ["python", "turtle", "web scraping", "qr code", "blog", "Tachyons", "Multilingual", "Stackbit"]

[author]
  name = "Malick Royce LAYINDE"
  email = "layinderoyce@gmail.com"

[languages]
  [languages.fr]
    title = "RoyLab: Code & Web"
    weight = 1
    contentDir = "content/fr"
    # languageDirection = 'rtl' for Right-To-Left languages


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "/images/logo1.png"
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/malick-layinde-825a78257/"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/Royce-LAYINDE"

[[params.ananke_socials]]
name = "medium"
url = "https://medium.com/@layinderoyce"
