baseURL = '/'
languageCode = 'en-us'
title = 'RoyLab: Code & Web'
theme = 'ananke'
tags = ["python"]
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"

[author]
  name = "Malick Royce LAYINDE"
  email = "layinderoyce@gmail.com"
  
[params]
  copyright = "Copyright © 2023 Malick Royce LAYINDE"
  recent_posts_number = 4

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      toc = true

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/malick-layinde-825a78257/"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/Royce-LAYINDE"

