[build]
  command = "hugo"
  publish = "public"
  
[build.environment]
  HUGO_VERSION = "0.136.5"
  HUGO_EXTENDED = "true"
  HUGO_ENV = "production"
  GO_VERSION = "1.23"
  NODE_ENV = "development"

[context.production.environment]
  HUGO_VERSION = "0.136.5"
  HUGO_EXTENDED = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.136.5"
  HUGO_EXTENDED = "true"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.136.5"
  HUGO_EXTENDED = "true"
